# Generated by Django 5.0.2 on 2025-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="signature",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
