# Generated by Django 5.0.2 on 2025-08-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_update_user_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("complete", "Complete"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
