# Generated by Django 5.0.2 on 2025-08-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_update_complaint_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="demand",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="quantity_of_good",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="registration_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("meter_linear", "Metr bieżący"),
                    ("meter_square", "Metr kwadratowy"),
                    ("meter_cubic", "Metr sześcienny"),
                    ("piece", "Sztuka"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="type",
            field=models.CharField(
                choices=[("guarantee", "Gwarancja"), ("warranty", "Rękojmia")],
                max_length=20,
            ),
        ),
    ]
