# Generated by Django 5.0.2 on 2025-08-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_complaint_fields_and_update_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="quantity_of_good",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
