# Generated by Django 5.0.2 on 2025-08-15 10:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_complaint_quantity_of_good"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="date_of_purchase",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="quantity_of_good",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
