# Generated by Django 5.0.2 on 2025-08-15 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_complaint_date_of_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
