# Generated by Django 5.0.2 on 2025-08-15 10:57

import api.models.action_history
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_user_column_to_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionhistory",
            name="email",
            field=models.ForeignKey(
                db_column="email",
                on_delete=models.SET(
                    api.models.action_history.deleted_user_placeholder
                ),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
