# Generated by Django 5.0.2 on 2025-08-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_fix_on_delete_behaviour"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correction", "Korekta"),
                    ("exchange", "Wymiana"),
                    ("add_goods", "Dosłanie towaru"),
                    ("add_item", "Dosłanie elementu"),
                    ("rejection", "Odrzucenie"),
                    ("discount", "Zniżka"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
