# Generated by Django 5.0.2 on 2025-08-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_decision_column_to_complaint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Complaint Decision",
                "verbose_name_plural": "Complaint Decisions",
            },
        ),
        migrations.AlterField(
            model_name="complaint",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="api.complaintdecision",
            ),
        ),
    ]
