# Generated by Django 5.0.2 on 2025-08-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_create_complaint_decision_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Complaint Status",
                "verbose_name_plural": "Complaint Statuses",
            },
        ),
        migrations.RemoveField(
            model_name="complaintdecision",
            name="code",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="api.complaintstatus",
            ),
        ),
    ]
