# Generated by Django 5.0.2 on 2025-08-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_create_complaint_status_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="unit", max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Registration Unit",
                "verbose_name_plural": "Registration Units",
            },
        ),
        migrations.AddField(
            model_name="complaintdecision",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="complaintstatus",
            name="code",
            field=models.CharField(default="not_started", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="api.complaintdecision",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="registration_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="api.registrationunit",
            ),
        ),
    ]
