# Generated by Django 5.0.2 on 2025-08-15 13:20

from django.db import migrations


def create_default_complaint_statuses(apps, schema_editor):
    ComplaintStatus = apps.get_model('api', 'ComplaintStatus')
    statuses = [
        {"code": "not_started", "label": "Nie rozpoczęto"},
        {"code": "in_progress", "label": "W trakcie"},
        {"code": "on_hold", "label": "Wstrzymano"},
        {"code": "complete", "label": "Zakończono"}
    ]
    for status in statuses:
        ComplaintStatus.objects.get_or_create(**status)


def create_default_registration_units(apps, schema_editor):
    RegistrationUnit = apps.get_model('api', 'RegistrationUnit')
    units = [
        {"code": "unit", "label": "Sztuka"},
    ]
    for unit in units:
        RegistrationUnit.objects.get_or_create(**unit)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_create_complaint_status_model"),
    ]

    operations = [
        migrations.RunPython(create_default_complaint_statuses),
        migrations.RunPython(create_default_registration_units),
    ]
