# Generated by Django 5.0.2 on 2025-08-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_registration_unit_model"),
        ("api", "0013_add_default_values"),
    ]

    operations = []
