# Generated by Django 5.0.2 on 2025-08-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_merge_20250815_1529"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, null=True, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Complaint Type",
                "verbose_name_plural": "Complaint Types",
            },
        ),
        migrations.AlterField(
            model_name="complaint",
            name="type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="api.complainttype",
            ),
        ),
    ]
