# Generated by Django 5.0.2 on 2025-08-15 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_add_complaint_type_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, null=True, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Action Type",
                "verbose_name_plural": "Action Types",
            },
        ),
        migrations.AlterModelOptions(
            name="actionhistory",
            options={"verbose_name_plural": "Action History"},
        ),
        migrations.AlterField(
            model_name="actionhistory",
            name="action",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_history",
                to="api.actiontype",
            ),
        ),
    ]
