# Generated by Django 5.0.2 on 2025-08-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_action_type_model"),
        ("api", "0017_create_default_values"),
    ]

    operations = []
