# Generated by Django 5.0.2 on 2025-08-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_merge_20250815_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="api.producer",
            ),
        ),
    ]
