# Generated by Django 5.0.2 on 2025-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_add_producer_column_to_complaint_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="quantity_of_good",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="complaint",
            name="commodity_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
