# Generated by Django 5.0.2 on 2025-08-16 11:30

import api.models.complaint
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_add_commodity_name_column_in_complaints_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="deadline",
            field=models.DateField(
                blank=True, default=api.models.complaint.default_deadline, null=True
            ),
        ),
    ]
